mutation SingIn($input: SignInInput!){
  signIn(input: $input) {
    id
  	username
		password
    status
    createdBy
    createdAt
    updatedAt
    token
    profile {
      id
      mobile
      firstName
      lastName
      birthday
      lineID
      email
      createdAt
      updatedAt
    }
    role {
      id
      name
      type
      thirdPartyInfo
      createdAt
      updatedAt
    }
  }
}
