query User($id: Int!) {
  user(id: $id) {
    id
    username
    password
    status
    createdBy
    createdAt
    updatedAt
    profile {
      id
      mobile
      firstName
      lastName
      birthday
      lineID
      email
      createdAt
      updatedAt
    }
    role {
      id
      name
      type
      thirdPartyInfo
      createdAt
      updatedAt
    }
  }
}
