query Users($status: UserStatus, $createdBy: CreatedBy, $offset: Int, $limit: Int) {
  users(status: $status, createdBy: $createdBy, offset: $offset, limit: $limit) {
    id
    roleId
    username
    password
    status
    createdBy
    createdAt
    updatedAt
    profile {
      id
      mobile
      firstName
      lastName
      birthday
      lineID
      email
      createdAt
      updatedAt
    }
    role {
      id
      name
      type
      thirdPartyInfo
      createdAt
      updatedAt
    }
  }
}
