query Website($id: Int!) {
  website(id: $id) {
    id
    user {
      id
      username
    }
    userId
    name
    domain
    subdomain
    settings
    status
    maintenance {
      id
      configType
      configStatus
      startDate
      endDate
      message
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
